const data = [
    {
      subject: 'Math',
      year: '2022',
      semester: '2',
      previouslyAskedIn: 'Midterm Exam',
      question: 'What is the formula for calculating the area of a circle?',
      answer: 'The formula for calculating the area of a circle is A = πr², where A is the area and r is the radius.'
    },
    {
      subject: 'History',
      year: '2021',
      semester: '1',
      previouslyAskedIn: 'Final Exam',
      question: 'Who was the first president of the United States?',
      answer: 'George Washington was the first president of the United States.'
    }
  ];

  